language: objective-c
osx_image: xcode7.2
branches:
  only:
  - "/^refactor\\/.*$/"
  - "/^feature\\/.*$/"
  - "/^bug\\/.*$/"
  - "/^test\\/.*$/"
  - "/^chore\\/.*$/"
  - "/^release.*$/"
notifications:
  email: false
before_install:
- brew update || brew update
- brew install carthage
- gem install scan
- scan --version
install: true
script:
- scan -p "RealmResultsController.xcodeproj" -s "RealmResultsController-iOS"
